apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.echo.example.com
spec:
  insecureSkipTLSVerify: true
  group: echo.example.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: api
    namespace: echo
  version: v1alpha1