apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: echo
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: echo-server
        image: docker.io/yanxue/http2-server
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: echo
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8000
  selector:
    apiserver: "true"